package com.github.pfmiles.dropincc.impl.runtime;

import com.github.pfmiles.dropincc.DropinccException;
import com.github.pfmiles.dropincc.impl.TokenType;
import com.github.pfmiles.dropincc.impl.runtime.impl.Lexer;

/**
 * The common interface of all language parsers generated by dropincc.java
 * 
 * @author pf-miles
 * 
 */
public abstract class Parser {

    protected Lexer lexer;

    /**
     * Parse the input and return the evaluated value, if any(AST or evaluated
     * results)
     * 
     * @return
     */
    public abstract <T> T parse(Object arg);

    /**
     * Set the lexer for this parser
     * 
     * @param lexer
     */
    public void setLexer(Lexer lexer) {
        this.lexer = lexer;
    }

    protected Object match(TokenType type) {
        Token ret = this.lexer.nextElement();
        if (!ret.getType().equals(type))
            throw new DropinccException("Unexpected token encountered: " + ret + ", expected type: " + type);
        return ret.getLexeme();
    }

}
