/*******************************************************************************
 * Copyright (c) 2012 pf_miles.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     pf_miles - initial API and implementation
 ******************************************************************************/
package com.github.pfmiles.dropincc.impl.runtime.impl;


/**
 * The common interface of all language parsers generated by dropincc.java
 * 
 * @author pf-miles
 * 
 */
public abstract class Parser {

    /**
     * Parse the input and return the evaluated value, if any(AST or evaluated
     * results)
     * 
     * @return
     */
    public abstract <T> T parse(Object arg);

    public abstract void setLexer(Lexer lexer);
}
